
# Continuous Integration
name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    name: Build on JDK11
    runs-on: ubuntu-latest

    steps:

    # ================================
    # SHALLOW CLONE
    # ================================
    - name: Shallow clone
      uses: actions/checkout@v3

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: 11

    # ================================
    # SETUP GRADLE
    # ================================
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

    # ================================
    # BUILD
    # ================================
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build -x check --info --scan

    # ================================
    # CHECK
    # ================================
    - name: Check
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check --info --scan
